### ISSUE TITLE
catchup doesn't download enough files in parallel

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1749]
# Issue type
  bug

# Version found
  10.0.0rc1

# Issue description
  It looks like the `MAX_CONCURRENT_SUBPROCESSES` setting is not fully respected.

## Actual result
Running with `MAX_CONCURRENT_SUBPROCESSES=32` and triggering catchup (that downloads many files at the same time), all I could see was this:
```
--bash---stellar-core---4*[gzip]
                     ¦+-7*[wget]
                     ¦+-3*[{stellar-core}]

```

## Expected result
I would expect to see around 32 processes (either `wget` or `gzip` in this example).

## Supporting files

```toml
PEER_PORT=12901
RUN_STANDALONE=false
LOG_FILE_PATH=""
BUCKET_DIR_PATH="/data/buckets"
HTTP_PORT=12900
PUBLIC_HTTP_PORT=true
NODE_IS_VALIDATOR=false
TARGET_PEER_CONNECTIONS=20
MAX_PEER_CONNECTIONS=30
MAX_CONCURRENT_SUBPROCESSES=32
PREFERRED_PEERS=["core-testnet1.stellar.org", "core-testnet2.stellar.org", "core-testnet3.stellar.org"]
FAILURE_SAFETY=0
UNSAFE_QUORUM=true
DATABASE="sqlite3://:memory:"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
AUTOMATIC_MAINTENANCE_PERIOD=60
AUTOMATIC_MAINTENANCE_COUNT=50000
[QUORUM_SET]
THRESHOLD_PERCENT=51
VALIDATORS=["GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y", "GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP", "GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z
"]


[HISTORY.core_testnet_001]
get="wget -q https://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-testnet/core_testnet_001/{0} -O {1}"


[HISTORY.core_testnet_002]
get="wget -q https://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-testnet/core_testnet_002/{0} -O {1}"


[HISTORY.core_testnet_003]
get="wget -q https://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-testnet/core_testnet_003/{0} -O {1}"

```
