### ISSUE TITLE
Consider processing buckets in memory in captive mode

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2942]
### Explain in detail the additional functionality you would like to see in stellar-core.

I think it's worth considering processing buckets directly while reading it from the archive (like in Go `ingest` package - see below) instead of saving the files on disk first. This could be set as a feature flag or a default behaviour when running Stellar-Core.

### Explain why this feature is important

Stellar-Core requires users to set `BUCKET_DIR_PATH` (or defaults to `buckets`). This is fine for normal Stellar-Core operations but in captive mode is inconvenient for the users. Captive Stellar-Core keeps entire state in memory so does not need access to a DB. However, it requires a large disk space for keeping the bucket files.

Captive Stellar-Core became default in [Horizon 2.0.0](https://github.com/stellar/go/releases/tag/horizon-v2.0.0) and saves bucket files to system tmp folder (`/tmp` by default in linux). Some users reported that this is an issue for them because they don't have enough disk space in `/tmp` partition. Currently it's not possible to overwrite `BUCKET_DIR_PATH` in Horizon (this is Horizon not Stellar-Core limitation). We can allow users to set it to a different value in the future version but processing files in memory would remove yet another setting completely and will make initial setup easier.

### Describe the solution you'd like

Something similar to [`CheckpointChangeReader`](https://github.com/stellar/go/blob/39409ffc7239/ingest/checkpoint_change_reader.go) used in `ingest` package and Horizon. The last time I checked memory usage of Go implementation it required around 300MB for processing and it can possibly decrease when old buckets are rewritten to `INITENTRY` ([CAP-20](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0020.md)). Please note that it's not a problem to check the bucket hash in this method (calculate SHA-256 hash online).

**Comment by MonsieurNicolas** [comment]
As we need full buckets all the time, including buckets getting merged, storing them directly in memory in core would increase the memory requirements substantially: right now the requirement is to have enough RAM to store a copy of the ledger.

Using `/tmp` is probably "good enough" in the short term, but this will probably will have to change at some point in the future because of the largest buckets (that are only used every few months).

Short term the solution if people want to keep buckets in memory is to just increase the size of `/tmp` (note: the default is that max size on Linux is half of the physical memory from what I found) or just point to a drive with enough disk space.

Note that even if we had an in memory version, we still need to download buckets, so the size requirement on `/tmp` is still high anyways as it needs to be able to store both compressed and uncompressed versions of the buckets before they get "ingested" by core.

Going into more detail on "in memory"...
An in memory version would more than triple this requirement without much traffic (because of merges in progress, in particular against the last level).
When adding "churn" to the ledger, we're now adding, on top of that memory requirement linear to the amount of changes in the ledger over potentially long periods of time: certain ledger entries "change all the time", which is actually fine (here we end up with something like ~6x the memory requirement), and for ledger entries that only exist for some time (like offers in the order book), we keep them around (potentially multiple copies) until the "delete" meets the "create" which depends on how long that offer existed for.

Note that we discussed moving to a different representation of the ledger + bucket list in memory before (not just for captive core), to avoid creating so many copies of the data in general, but this not on the list for now given where we are performance wise and it is a significant engineering investment.

**Comment by ire-and-curses** [comment]
Can you clarify: what size is "6x the memory requirement"? Is this 6x the 300MB @bartekn quoted? Or 6x the ledger size (i.e. 18GB)?

**Comment by MonsieurNicolas** [comment]
I don't know what those 300MB would correspond to in core as we need to keep all buckets.

In core we care about churn, which is related to how many "bytes" are changed per ledger which is related to operations/ledger so changes a lot depending on what people do on the network (so betting that this number stays low is a bad bet).

The 6x is a guesstimate on top of churn to compute a low watermark. In theory it can be more than 9x of churn as we have 10 levels of bucket list (again, much  higher peaks when merges are in progress/done - with level 9 merge sticking around for months at a time).

Outside of churn, merges are probably the big one for that we're looking at with more than 2x on top of the total ledger size because of that last merge.

**Comment by bartekn** [comment]
> As we need full buckets all the time, including buckets getting merged, storing them directly in memory in core would increase the memory requirements substantially: right now the requirement is to have enough RAM to store a copy of the ledger.

Is it required for Stellar-Core that is not writing history archives?

> Note that even if we had an in memory version, we still need to download buckets, so the size requirement on /tmp is still high anyways as it needs to be able to store both compressed and uncompressed versions of the buckets before they get "ingested" by core.

This is not what I suggested. In Horizon (in `ingest` package used by Horizon to be exact) we don't store the files but we process them while reading from history archive. It's possible because we can uncompress, decode XDR and calculate SHA-256 for hash validation by reading small chunks of data.

> I don't know what those 300MB would correspond to in core as we need to keep all buckets.

The 300MB I'm referring to is a size of map that keeps _seen_ ledger entries. The details of the algorithm can be checked [here](https://github.com/stellar/go/blob/74d2fd458f1abc800d6c2063031128ed56bade53/ingest/checkpoint_change_reader.go#L140-L162).

**Comment by MonsieurNicolas** [comment]
> Is it required for Stellar-Core that is not writing history archives?

Yeah we need the bucket hashes to make sure we're on the same ledger than the network, otherwise we would not have any of those problems.

> The 300MB I'm referring to is a size of map that keeps seen ledger entries. The details of the algorithm can be checked here.

Oh I see, this is to build the current ledger state - we do this currently with pretty much no overhead memory wise, just a lot slower. We talked to moving to something faster before but definitely not needed for now.

**Comment by bartekn** [comment]
OK, I think we can close this because bucket files are required for normal operations.

However, I'll use this issue to ask another question. We are thinking about possible changes to Horizon config format (ex. replace command line flags with toml). One of the things we'd like to fix is duplication (ex. now you need to set network passphrase both in Stellar-Core in Horizon). We started wondering about history archives: Horizon requires a plain URL however Stellar-Core needs a command (usually `curl`) that will be executed to download files. Is it possible / how hard is it to move the download functionality into Stellar-Core codebase to avoid using external commands?

**Comment by MonsieurNicolas** [comment]
We'd have to implement/take a dependency on some http client code and we don't really want to do this (if we want to support https we also have to take a dependency on openssl etc).

That said, if what you're trying to do is avoid duplication between captive-core and Horizon configs, you could just read the core config and extract the bits that you want from it.

Alternatively, you could avoid having to understand the core config schema completely by generating it from a template that way you let people specify whatever they want in the core config and let Horizon fill placeholders. The challenge in that direction (for archives) is that you're going to diverge from just being able to use the same core config everywhere.

Something like this (there are probably better things to do syntax wise):

```toml

HTTP_PORT=${{CORE_HTTP_PORT}}
PUBLIC_HTTP_PORT=false

NETWORK_PASSPHRASE=${{NETWORK_PASSPHRASE}}

DATABASE="sqlite3://stellar.db"

# Stellar Testnet validators
[[HOME_DOMAINS]]
HOME_DOMAIN="testnet.stellar.org"
QUALITY="HIGH"

[[VALIDATORS]]
NAME="sdftest1"
HOME_DOMAIN="testnet.stellar.org"
PUBLIC_KEY="GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y"
ADDRESS="core-testnet1.stellar.org"
HISTORY="curl -sf ${{HISTORY_ROOT[sdftest1]}}/{0} -o {1}"

# here is another way to do it
[[VALIDATORS]]
NAME="sdftest2"
HOME_DOMAIN="testnet.stellar.org"
PUBLIC_KEY="GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP"
ADDRESS="core-testnet2.stellar.org"
HISTORY=${{HISTORY_GET_COMMAND[sdftest2]}}

# maybe just allow something else entirely, like:
[[VALIDATORS]]
NAME="sdftest3"
HOME_DOMAIN="testnet.stellar.org"
PUBLIC_KEY="GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z"
ADDRESS="core-testnet3.stellar.org"

# this gets replaced by a bunch of `[HISTORY.foo]` blocks
${{DEFAULT_ARCHIVES}}
```
