### ISSUE TITLE
Derive Master Network Seed using a core command

### ISSUE THREAD

**Issue by brahman81** [stellar/stellar-core#3647]
### Explain in detail the additional functionality you would like to see in stellar-core.

We are trying to determine the master network seed automatically from the `NETWORK_PASSPHRASE` in order to bootstrap new networks programmatically.

This is possible by running a `stellar-core new-db` command with a valid configuration but requires setting up a config and launching a node but this requires knowing stellar-core.cfg format and required configuration items before being able to launch the node and extract the seed from the log file.

Ideally we would be able to run `stellar-core --network-passphrase "DemoNet ; January 2023"` and receive a blob with SEED and Public key which we can then use in our automation.

**Comment by brahman81** [comment]
@stanford-scs this functionality could also live in https://github.com/xdrpp/stc/ for ease of use ?

**Comment by MonsieurNicolas** [comment]
I imagine that this is in the context of some automation that submits transactions? If so, this functionality should be included in pretty much all SDKs.

**Comment by MonsieurNicolas** [comment]
and by that, I mean it's already included in SDKs

**Comment by brahman81** [comment]
Thanks @MonsieurNicolas , I checked the JS sdk but couldn't find any examples of passing the passphrase and getting the master network seed.

**Comment by brahman81** [comment]
Looking at this in more detail, I think the below snippet will work:

```javascript
var masterKeypair = StellarSdk.Keypair.master("Custom Network ; January 2023");
var masterAccount = new StellarSdk.Account(masterKeypair.publicKey(), "0");
```

**Comment by MonsieurNicolas** [comment]
yes this is it

**Comment by anupsdf** [comment]
Closing this since there is a workaround to derive using StellarSdk. Nothing needed from core side.

**Comment by leighmcculloch** [comment]
You can also do:

Mac:
```
$ stellar-core convert-id $(printf "Test SDF Network ; September 2015" | shasum -a 256 | cut -f 1 -d " ")
```

Some linux's:
```
stellar-core convert-id $(printf "Test SDF Network ; September 2015" | sha256sum | cut -f 1 -d " ")
```

And the output will be:
```
PublicKey:
  strKey: GDHOAMBNLGCE2MV5ZKIVZAQD3VCLGP53P3OBSBI6UN5L5XZI5TKHEUYD
  hex: cee0302d59844d32bdca915c8203dd44b33fbb7edc19051ea37abedf28ecd472
Seed:
  strKey: SDHOAMBNLGCE2MV5ZKIVZAQD3VCLGP53P3OBSBI6UN5L5XZI5TKHFQL4
PublicKey:
  strKey: GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H
  hex: 62fc1d0bd091b2b61c0dd656346b2a68d7d347c6f2c2c8ee6d04470256fc05f7
```

We use this in the quickstart docker image:
https://github.com/stellar/quickstart/blob/ff3dd50ad402c19c4487e7a322b0746793004dae/start#L198C3-L201
