### ISSUE TITLE
Catchup hash mismatch (Version: v20.0.0-rc2)

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-core#3958]
## Issue Description

Running stellar-core normally connected to testnet results in periodic "Catchup material failed verification - hash mismatch" errors.

## Steps to Reproduce

Unknown at this time. This has occurred three times when running stellar-core in the quickstart image connected to the testnet network as a watcher node.

```
docker run --name stellar -p 8000:8000 stellar/quickstart:testing --testnet --enable-soroban-rpc
```

No other action has been required to my knowledge.

### stellar-core Version
```console
$ stellar-core version
Warning: soroban-env-host-curr is running a pre-release version 20.0.0-rc1
v20.0.0rc2
rust version: rustc 1.72.1 (d5c2e9c34 2023-09-13)
soroban-env-host: 
    curr:
        package version: 20.0.0-rc1
        git version: f19ef13363a1e0cbff7b100c0599a1d63dea88a6
        ledger protocol version: 20
        pre-release version: 57
        rs-stellar-xdr:
            package version: 20.0.0-rc1
            git version: d5ce0c9e7aa83461773a6e81662067f35d39e4c1
            base XDR git version: 9ac02641139e6717924fdad716f6e958d0168491
```

### Environment
* Operation System & Version (You can usually obtain from `uname -a`)
   
   ```console
   $ uname -a
   Linux 781545c4c81d 6.3.13-linuxkit #1 SMP PREEMPT Thu Sep  7 07:48:47 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
   ```

* Are you running from the command line? From a container?

   Both. Command line inside a container running inside a VM managed by Docker for Mac on an Apple Silicon M2 Mac.

* Did you pass in special parameters when building the app?

   The `stellar/quickstart:testing` image has stellar-core compiled with the `--disable-tests` option.

* Please add any additional relevant configuration related to this bug report.

   The `stellar/quickstart:testing` image is a multi-platform image and when this issue occurred I was running it using the `linux/arm64` platform image. To run specifically that image you can pass to docker `--platform linux/arm64` or if using a container runtime that doesn't support specifying the platform the same image is available as a single-platform image under the name `stellar/quickstart:testing-arm64`.

## Supporting Files

* Configuration files

   The configuration file template used for testnet in quickstart is here:
   https://github.com/stellar/quickstart/blob/140ee88feb0d265120255827f0e2e1dae04d6da5/testnet/core/etc/stellar-core.cfg#L3

   Once the template is fully rendered it is:
   ```toml
   HTTP_PORT=11626
   PUBLIC_HTTP_PORT=true
   LOG_FILE_PATH=""
   MANUAL_CLOSE=false
   
   NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
   KNOWN_CURSORS=["HORIZON"]
   DATABASE="postgresql://dbname=core host=localhost user=stellar password=..."
   CATCHUP_RECENT=100
   
   UNSAFE_QUORUM=true
   FAILURE_SAFETY=1
   
   [[HOME_DOMAINS]]
   HOME_DOMAIN="testnet.stellar.org"
   QUALITY="HIGH"
   
   [[VALIDATORS]]
   NAME="sdf_testnet_1"
   HOME_DOMAIN="testnet.stellar.org"
   PUBLIC_KEY="GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y"
   ADDRESS="core-testnet1.stellar.org"
   HISTORY="curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_001/{0} -o {1}"
   
   [[VALIDATORS]]
   NAME="sdf_testnet_2"
   HOME_DOMAIN="testnet.stellar.org"
   PUBLIC_KEY="GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP"
   ADDRESS="core-testnet2.stellar.org"
   HISTORY="curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_002/{0} -o {1}"
   
   [[VALIDATORS]]
   NAME="sdf_testnet_3"
   HOME_DOMAIN="testnet.stellar.org"
   PUBLIC_KEY="GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z"
   ADDRESS="core-testnet3.stellar.org"
   HISTORY="curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_003/{0} -o {1}"
   ```

* Log files

   ```
   2023-09-20T21:36:16.487 GDHDX [History ERROR] Catchup material failed verification - hash mismatch, propagating failure
   2023-09-20T21:36:16.487 GDHDX [History ERROR] One or more of history archives may be corrupted. Update HISTORY configuration entry to only contain valid ones
   ```

   Full log of stellar-core stderr output is attached: [full-log-2023-09-20.txt](https://github.com/stellar/stellar-core/files/12807059/full-log-2023-09-20.txt).

* Status – the status of stellar-core on its info endpoint was cycling on these:

   ```
   Catching up; Catching up to ledger 1619071: downloading ledger files 1/1 (100%)
   Catching up; Catching up to ledger 1619071: Failed: download-verify-ledgers-seq
   Catching up; Catching up to ledger 1619071: Succeeded: batch-download-ledger-0018b47f-0018b4bf : 1/1 children completed
   Catching up; Catching up to ledger 1619071: Succeeded: batch-download-ledger-0018b47f-0018b4bf : 2/2 children completed
   Catching up; Catching up to ledger 1619071: Succeeded: batch-download-ledger-0018b47f-0018b4bf : 3/3 children completed
   Catching up; Catching up to ledger 1619071: Succeeded: batch-download-ledger-0018b47f-0018b4bf : 4/4 children completed
   Catching up; Catching up to ledger 1619071: Succeeded: batch-download-ledger-0018b47f-0018b4bf : 5/5 children completed
   ```

## Discussions

There has been some offline discussion on Slack about this issue:
- https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1695245597931859 involving @dmkozh @graydon @anupsdf @MonsieurNicolas @marta-lokhova @leighmcculloch 
- https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1696378569793859 involving @graydon @MonsieurNicolas @leighmcculloch
